# Generated by Django 5.2 on 2025-05-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.JSONField()),
                ('instructions', models.TextField()),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('meal_type', models.CharField(max_length=50)),
                ('suitable_trimesters', models.CharField(default='1,2,3', max_length=20)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, null=True)),
                ('carbs', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('folate', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_dairy_free', models.BooleanField(default=False)),
                ('contains_allergens', models.JSONField(default=list)),
                ('good_for_anemia', models.BooleanField(default=False)),
                ('good_for_gestational_diabetes', models.BooleanField(default=False)),
                ('good_for_hypertension', models.BooleanField(default=False)),
                ('good_for_morning_sickness', models.BooleanField(default=False)),
            ],
        ),
    ]
